# vim: set ts=2 sts=2 sw=2:
from subleekr.www.models import Site


SITES = [
  ("internals", [
    Site("sublee.kr",
         "http://sublee.kr/",
         "Just here.",
         icon=True),
    Site("lab.sublee.kr",
         "http://lab.sublee.kr/",
         "My laboratory.",
         icon=True),
    Site("readme.sublee.kr",
         "http://readme.sublee.kr/",
         "My blog.",
         icon="http://lab.sublee.kr/favicons/readme.sublee.kr.ico"),
    Site("docs.sublee.kr",
         "http://docs.sublee.kr/",
         "The documentations in my laboratory.",
         icon=True),
    Site("me2apps.sublee.kr",
         "http://me2apps.sublee.kr/",
         "Applications(developed by me) for me2DAY.",
         icon=True),
    Site("ubiq.sublee.kr",
         "http://ubiq.sublee.kr/",
         "The ubiquitous system for my personal room.",
         icon="http://ubiq.sublee.kr/static/favicon.ico"),
    Site("limbo.sublee.kr",
         "http://limbo.sublee.kr/",
         "The virtual server maintained by me.",
         icon=True),
#    Site("history.sublee.kr",
#         "http://history.sublee.kr/",
#         "The history of my hompages.",
#         icon="http://lab.sublee.kr/favicons/history.sublee.kr.ico"),
#    Site("hire.sublee.kr",
#         "http://hire.sublee.kr/",
#         "The history of my hompages.",
#         icon="http://lab.sublee.kr/favicons/hire.sublee.kr.ico"),
#    Site("game.sublee.kr",
#         "http://game.sublee.kr/",
#         "The history of my hompages.",
#         icon="http://lab.sublee.kr/favicons/game.sublee.kr.ico"),
  ]),
  ("projects", [
    Site("Flask-AutoIndex",
         "http://packages.python.org/Flask-AutoIndex/",
         "Generates index page like mod_autoindex for Flask application.",
         icon="http://packages.python.org/Flask-AutoIndex"
              "/_static/favicon.ico"),
    Site("DocTest.js",
         "http://lab.sublee.kr/doctest.js",
         "An interactive JavaScript test framework.",
         icon="http://lab.sublee.kr/doctest.js/favicon.ico"),
    Site("VLAAH",
         "http://vlaah.com/",
         "A social network service focuses on favorites of people.",
         icon="http://lab.sublee.kr/favicons/vlaah.com.ico"),
#    Site("AwtoIndex",
#         "http://lab.sublee.kr/awtoindex",
#         "More awesome Apache2's mod_autoindex."),
    Site("Vlastic",
         "http://vlastic.ruree.net/",
         "A web framework for Python 3.0."),
    Site("me2PHeungP",
         "http://bitbucket.org/heungsub/me2pheungp",
         "me2DAY API client library for PHP.",
         icon="http://lab.sublee.kr/favicons/sublee.kr-apps-me2pheungp.ico"),
    Site("PagedTable",
         "http://lab.sublee.kr/pagedtable",
         "A pager for the HTML table with jQuery."),
  ]),
  ("externals", [
    Site("GitHub",
         "http://github.com/sublee",
         "My git repositories.",
         icon="/static/github.com.ico"),
    Site("Flickr",
         "http://www.flickr.com/photos/heungsub",
         "My photos.",
         icon=True),
    Site("YouTube",
         "http://www.youtube.com/lhs8912",
         "My videos.",
         icon=True),
    Site("VLAAH",
         "http://vlaah.com/heungsub",
         "My favorites.",
         icon="http://static.vlaah.com/images/favicon.ico"),
    Site("me2DAY",
         "http://me2day.net/sub",
         "My micro blog.",
         icon=True)
  ])
]

